#!/usr/bin/env bash
# Displays 1 to 20 with superstitious number messages
i=1
while [ $i -le 20 ]; do
    echo "$i"
    case $i in
        4)  echo "bad luck from China" ;;
        9)  echo "bad luck from Japan" ;;
        17) echo "bad luck from Italy" ;;
    esac
    i=$((i + 1))
done
