#!/usr/bin/env bash
# Creates PID file, traps SIGTERM, SIGINT, SIGQUIT, and cleans up on termination

echo "$$" > /var/run/myscript.pid

cleanup() {
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'echo "I hate the kill command"; cleanup' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'cleanup' SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
